### ISSUE TITLE
What does setting prototype of instantiator to constructor achieve? 

### ISSUE THREAD

**Issue by trusktr** [Mr0grog/newless#12]
https://github.com/Mr0grog/newless/blob/3fe059f3f8ac26d945afb01c880dd68d2e61d631/newless.js#L43

What does that achieve?

**Comment by Mr0grog** [comment]
Early versions of Safari 9 looked up the super class based on the constructor property, not the prototype chain (that’s incorrect by spec, but ¯\\\_(ツ)\_/¯ ). IIRC it got fixed partway through the Safari 9 line, but maybe it wasn’t until 10.

**Comment by Mr0grog** [comment]
Oh, oops, I misread and thought you were talking about the line below 43. In compliant engines, this `setPrototype()` call makes sure the right constructor is called.

Let’s say you have a hierarchy like:

```js
class Z { constructor() {...} }
class Y extends Z { constructor() {...} }
function X { return Reflect.construct(Y, args, X); }
```

To make sure the inheritance chain of the resulting object is correct, our `instantiator` class inherits from `X`. But the actual function we want to *run* is `Y`. If we did nothing else, `new instantiator` would run the constructor logic in `X`. But what we actually wanted here was to run `Y`.

A class with no `constructor` looks up the super constructor to call by checking its `__proto__`. In other words, it executes its implicit `super()` call by doing something like `Object.getPrototypeOf(instantiator)()` on an engine level.
