### ISSUE TITLE
Many setPrototypeOf calls on the instantiated value of class hierarchy in Reflect.construct polyfill.

### ISSUE THREAD

**Issue by trusktr** [Mr0grog/newless#14]
https://github.com/Mr0grog/newless/blob/3fe059f3f8ac26d945afb01c880dd68d2e61d631/newless.js#L66

If I understand correctly, if there is a class hierarchy, an each constructor uses `Reflect.construct` with the same `new.target` passed as third arg to `Reflect.construct`, then that line will set the prototype of the return value as many times as there are number of classes in the class hierarchy.

So, if we have Baz which extends Bar which extends Foo, then `Object.setPrototypeOf` will be called three times, right? The outer Reflect.construct call in Baz will cause the Reflect.construct call in Bar to cause the Reflect.construct call in Foo, so then Foo returns the value after setting value's prototype, then Bar returns the value after setting value's prototype again, then finally Baz returns the value after setting value's prototype to the final Baz.prototype.

Is there a better way? Maybe we can store the newTarget of the top-level Reflect.construct call outside the scope of Reflect.construct, then just set the prototype of value only once when we detect we're back at the top level Reflect.construct call?

It just seems absurd that we have to go through this just to extend ES2015+ classes using ES5 style classes. Spec people should've made all builtin classes compatible with ES5 classes rather than fixing the problem in a way that makes new classes restrictive and inflexible.

**Comment by Mr0grog** [comment]
> that line will set the prototype of the return value as many times as there are number of classes in the class hierarchy.

It’s been a while, but IIRC, this is what I added `TRUE_CONSTRUCTOR` for (see [the comment about performance here](https://github.com/Mr0grog/newless/blob/57b9b1b029dc63dab21022937fc8bda9375cb2ea/newless.js#L184-L194)). We swap things out so that we only ever have to call `Reflect.construct()` (or the polyfill here) once (by calling it on `TRUE CONSTRUCTOR`) rather than continually popping in-and-out of engine-level class construction because we have newless classes in-between at each inheritance level as you’re describing.

I didn’t like having that extra property hanging around and swapping things out, but it seemed the only way to work around exactly the issue you are wondering about :)

**Comment by Mr0grog** [comment]
> It just seems absurd that we have to go through this just to extend ES2015+ classes using ES5 style classes. Spec people should've made all builtin classes compatible with ES5 classes rather than fixing the problem in a way that makes new classes restrictive and inflexible.

For what it’s worth, you could get away with doing *way* less than this library does if you just want to manually construct a class and aren’t worried about weird bugs in versions of browsers that only half-implemented ES6. I know you’re active on the web components repo, and if that’s your use-case, you really don’t need most of the rigamarole here—web components only exist in browsers without those bugs.

This library might be a bit more abstract or broad in scope than what you need.

**Comment by trusktr** [comment]
In [lowclass](https://github.com/trusktr/lowclass) I have started working around it by using a stack, pushing to it when `new.target` is not the same (f.e. some constructor calls `new OtherConstructor`, and then popping after OtherConstructor is finished). Not sure if that makes sense in so few words, but it's WIP that I want to push soon. At the moment (what's pushed to the repo) in lowclass is purely ES5 classes, but I'm working to get it working with ES6+ classes, so I was looking for some clues here. :)

> I know you’re active on the web components repo, and if that’s your use-case

Yep, that's my use case, but now I'm inside the rabbit hole. My goal is to make classes with the public/protected/private feature that I have in lowclass (see test.js for examples), and be able to use them where ES6+ classes are required (f.e. Custom Elements).
