### ISSUE TITLE
extending Array

### ISSUE THREAD

**Issue by trusktr** [Mr0grog/newless#16]
I thought I'd give it a try:

![image](https://user-images.githubusercontent.com/297678/38074060-52e7c20e-32e2-11e8-97af-c518cf6a2d0d.png)

Seems to slightly work (f.e. `.push(1,2,3)` does push those values, but `.concat` treats my instance as a single item and does not flatten it.

Can we achieve this with newless?

**Comment by Mr0grog** [comment]
Did you read https://github.com/Mr0grog/newless#caveats ? This is basically the same scenario and the way to handle it is written out there.

**Comment by trusktr** [comment]
Without newless, I'm trying to see if I can get close:

```js
function MyArray() {
  const array = new Array
  Object.setPrototypeOf( array, MyArray.prototype )
  Object.setPrototypeOf( this, array )
}
MyArray.prototype = Object.assign(Object.create(Array.prototype), {
  add(...args) {
    this.push(...args)
  }
})
Object.setPrototypeOf(MyArray, Array)
MyArray[Symbol.species] = Array

const a = new MyArray

a.add(1,2,3)
a.concat([4,5,6]) instanceof MyArray // false, plus still same problem as above
a instanceof MyArray // true
```

Is that as close as we can get? Is this regarding the limitation about the two contexts (where like in my example I've made the array instance prototype of `this`), and that for regular `class`es this should mostly work, but Array still requires to be extended with native `class`? Or is there a way?

**Comment by trusktr** [comment]
I tried with `Reflect.construct` but no luck:

```js
{
function MyArray() {
  const array = Reflect.construct(Array, [], new.target)
  console.log(array.__proto__ === MyArray.prototype)
  //Object.setPrototypeOf( array, MyArray.prototype ) // done by Reflect.construct
  Object.setPrototypeOf( this, array )
}
MyArray.prototype = Object.assign(Object.create(Array.prototype), {
  add(...args) {
    this.push(...args)
  }
})
Object.setPrototypeOf(MyArray, Array)
MyArray[Symbol.species] = MyArray

const a = new MyArray
a.add(1,2,3) // works
a.concat([4,5,6]) // [ MyArray(3), 4, 5, 6 ]
a.concat([4,5,6]) instanceof MyArray // false
}
```

Note, I tried with `MyArray` as species this time, no luck with that either. I was hoping Reflect.construct and species were the tools to make this happen if not using `class`es. Did I miss something?

**Comment by trusktr** [comment]
> Did you read https://github.com/Mr0grog/newless#caveats ? This is basically the same scenario and the way to handle it is written out there.

Just saw your comment late (GitHub should auto refresh consistently!). I saw that caveat, but I wasn't sure if it was the same.

**Comment by trusktr** [comment]
I tried returning the value, but the README didn't say to change the prototype of the return value to SubConstructor.prototype. So this mostly works:

```js
function MyArray(...args) {
  const array = (newless(Array)).call(this, ...args)
  array.__proto__ = MyArray.prototype // this line is required
  return array
}

MyArray.prototype = Object.assign(Object.create(Array.prototype), {
  add(...args) {
    this.push(...args)
  }
})

Object.setPrototypeOf(MyArray, Array)
MyArray[Symbol.species] = Array

const a = new MyArray

a.add(1,2,3)
a.concat([4,5,6]) // [1,2,3,4,5,6]
```

but still:

```js
a.concat([4,5,6]) instanceof MyArray // false
```

I guess the `species` thing would be a bonus to get that working. Is it possible?

For now, I can do this:

```js
MyArray.from(a.concat([4,5,6])) instanceof MyArray // true
```

That also hints that I can make my own concat:

```js
MyArray.prototype.concat = function concat(...args) {
  return MyArray.from( Array.prototype.concat.call(this, ...args) )
}
```

And probably what I'd need to do is autogenerate those methods from a whitelist of methods that require wrapping.

**Comment by Mr0grog** [comment]
So you’ve got a few problems here:

```js
function MyArray() {
  const array = Reflect.construct(Array, [], new.target)
  Object.setPrototypeOf( this, array )
}
// OR (same problem):
function MyArray() {
  const array = new Array
  Object.setPrototypeOf( array, MyArray.prototype )
  Object.setPrototypeOf( this, array )
}
```

Arrays are a special kind of object (in spec terms, “array exotic object”). You can *only* create one by calling the Array constructor (or `Reflect.construct`-ing the Array constructor or `super()`-ing your way to it). So in `MyArray` here, `array` is an array exotic, but `this` is *not.* That’s why `a.concat(...)` is winding up as `[{obj}, 4, 5, 6]`. You *have* to return `array` from `MyArray` (see also the caveat in the README here).

The second problem is that the result of `MyArray` has `constructor === Array`! The species symbol is found by the engine inside `concat` by doing `this.constructor[Symbol.species]` (technically there a few more checks in there, but that’s mainly it). So your constructor needs to be like this if you want it to work:

```js
function MyArray() {
  const array = Reflect.construct(Array, [], new.target)
  array.constructor = new.target
  return array
}
```

**Comment by Mr0grog** [comment]
FWIW, [the spec](https://tc39.github.io/ecma262/) is actually pretty clear on a lot of this stuff and can be a great aid in understanding what you have to do to get the result you want.

**Comment by trusktr** [comment]
Ah, the constructor property, I forgot that. It's been a while since I've written ES5 classes, and they're automatic in ES6 classes.

**Comment by trusktr** [comment]
Alright, I got the hang of it with versions that aren't pure ES5, and one version that is as close to ES5 as possible but using `__proto__`. In the following examples, all assertions pass:

```js
const assert = console.assert.bind( console )

//**Using `newless` with some ES2015+ language features:**
{
  function MyArray(...args) {
    const self = (newless(Array)).call(this, ...args)
    self.__proto__ = MyArray.prototype
    return self
  }

  MyArray.prototype = {
    __proto__: Array.prototype,
    constructor: MyArray,

    add(...args) {
      this.push(...args)
    },
  }

  MyArray.__proto__ = Array

  const a = new MyArray
  assert( a instanceof MyArray )

  a.add(1,2,3)
  assert( a.length === 3 )
  assert( a.concat(4,5,6).length === 6 )
  assert( a.concat(4,5,6) instanceof MyArray )
  assert( Array.isArray(a) )
}

//**Without `newless` but still with some ES2015+ language features:**
{
  function MyArray(...args) {
    const self = new Array(...args)
    self.__proto__ = MyArray.prototype
    return self
  }

  MyArray.prototype = {
    __proto__: Array.prototype,
    constructor: MyArray,

    add(...args) {
      this.push(...args)
    },
  }

  MyArray.__proto__ = Array

  const a = new MyArray
  assert( a instanceof MyArray )

  a.add(1,2,3)
  assert( a.length === 3 )
  assert( a.concat(4,5,6).length === 6 )
  assert( a.concat(4,5,6) instanceof MyArray )
  assert( Array.isArray(a) )
}

//**With Reflect.construct, and ES2015+ language features:**
{
  function MyArray(...args) {
    return Reflect.construct(Array, args, new.target)
  }

  // with ES6+ features:
  MyArray.prototype = {
    __proto__: Array.prototype,
    constructor: MyArray,

    add(...args) {
      this.push(...args)
    },
  }

  MyArray.__proto__ = Array

  const a = new MyArray
  assert( a instanceof MyArray )

  a.add(1,2,3)
  assert( a.length === 3 )
  assert( a.concat(4,5,6).length === 6 )
  assert( a.concat(4,5,6) instanceof MyArray )
  assert( Array.isArray(a) )
}

//**ES5-ish version, but uses non-standard __proto__ which may not be available ES5 engines:**
~function() {
  function MyArray() {

    // we need the null for the following bind call
    var args = [null].concat( Array.prototype.slice.call(arguments) )

    var self = new ( Array.bind.apply(Array, args) )
    self.__proto__ = MyArray.prototype

    return self
  }

  function assign(target, source) {
    // naive implementation, can be improved
    for (var key in source) {
      target[key] = source[key]
    }
    return target
  }

  MyArray.prototype = assign( Object.create(Array.prototype), {
    constructor: MyArray,
    add: function() {
      this.push.apply(this, Array.prototype.slice.call(arguments))
    },
    concat: function() {
      var args = Array.prototype.slice.call(arguments)
      return MyArray.from( Array.prototype.concat.apply( this, args ) )
    },
  })

  Array.from = function( other ) {
    var result = new this

    other.forEach( function( item, index ) {
      result[index] = item
    })

    return result
  }

  assign(MyArray, Array) // static inheritance in ES5, but note naive assign implementation fails with non-enumerables
  MyArray.from = Array.from // in case from is non-enumerable (f.e. this ES5 code in ES6 environment)
  //MyArray[Symbol.species] = Array // doesn't exist in ES5

  var a = new MyArray
  assert( a instanceof MyArray )

  a.add(1,2,3)
  assert( a.length === 3 )
  assert( a.concat(4,5,6).length === 6 )
  assert( a.concat(4,5,6) instanceof MyArray )
  assert( Array.isArray(a) )
}()
```

But, what I'm wondering is how to do it in pure ES5 (no `__proto__`) and there doesn't seem to be a way to modify the prototype after the fact. I've tried the following but it obviously fails the assertions:

```js
  function MyArray() {

    // we need the null for the following bind call
    var args = Array.prototype.slice.call(arguments)

    var self = Object.create( MyArray.prototype )
    self = Array.apply( self, args ) || self

    return self
  }
```

Is there some way to make it work in pure ES5?

**Comment by trusktr** [comment]
Well, the good thing is, everything I'm targetting has `__proto__`, so at least I can use that. Still curious about a "pure ES5" version, if possible, just for learning.

**Comment by Mr0grog** [comment]
> Is there some way to make it work in pure ES5?

No. One of the *primary selling points* of ES6 class syntax was the ability to subclass builtins and potentially exotic objects. You cannot do this without either class syntax or Reflect.construct.

**Comment by trusktr** [comment]
> You cannot do this without either class syntax or Reflect.construct.

Also with `__proto__` in ES5 engines that have it.

> One of the primary selling points of ES6 class syntax was the ability to subclass builtins and potentially exotic objects.

But it makes traditional patterns fail. It should've been fixed another way rather than making people use a new pattern that isn't practically non-backwards-compatible.
