### ISSUE TITLE
Unable to extend HTMLElement and use with Custom Elements.

### ISSUE THREAD

**Issue by trusktr** [Mr0grog/newless#17]
I gave a try to using `newless` with Custom Elements:

```js
const HtmlElement = newless(HTMLElement)
customElements.define('my-el', HtmlElement)
const el = document.createElement('my-el')
```

which results in:

```
VM2656:3 Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at new HTMLElement (eval at newless (:536:30), <anonymous>:3:331)
    at <anonymous>:610:21
```

Can it work? Is it failing to detect `requiresNew`?

**Comment by trusktr** [comment]
If I try a slightly more complex example, it fails with a different error:

```js
const HTMLElement = newless(window.HTMLElement)
HTMLElement.subclass = Class
const MyEl = HTMLElement.subclass('MyEl', () => ({
  connectedCallback() {
    console.log(' ----- connected!')
  }
}))
customElements.define('my-el', MyEl)
const el = document.createElement('my-el')
document.body.appendChild( el )
```

where behind the scenes `Class` is using just simple ES5-style classes which call the parent constructor with a simple `parent.apply(this)`.

The error is:

```
Uncaught TypeError: Failed to construct 'CustomElement': The result must implement HTMLElement interface
    at <anonymous>:616:21
```

I was hoping `newless` would come in handy here, so that my `Class` implementation would be able to define the subclass using just basic ES5 `ctor.apply(this)`.

What do we have to do to make ES5 classes that work with Custom Elements?

**Comment by trusktr** [comment]
Okay, interesting, if I do the following it works great!

```js
function MyEl(...args) {
  const self = (newless(HTMLElement)).call(this, ...args)
  self.__proto__ = MyEl.prototype
  return self
}

MyEl.prototype = {
  __proto__: HTMLElement.prototype,
  constructor: MyEl,

  connectedCallback() {
    console.log(' ----- connected!')
  },
}

MyEl.__proto__ = HTMLElement

customElements.define('my-el', MyEl)
const el = document.createElement('my-el')
document.body.appendChild( el )

// logs: " ----- connected!"
```

This means I must be messeing it up in my `Class` impl.

**Comment by Mr0grog** [comment]
I’m going to close this, then.

**Comment by trusktr** [comment]
Alright, after making the `new.target` change (https://github.com/Mr0grog/newless/pull/20), I had to catch a different error message for `HTMLElement` to work properly: https://github.com/Mr0grog/newless/pull/21
